; ======================================================
; TESTE 2: RESOLUCAO DE EQU E IF
; ======================================================
FALSO EQU 0
VERDADE EQU 1
VALOR_CONST EQU 15

SECTION TEXT
INPUT NUM1

IF FALSO
ADD NUM1 ; ESTA LINHA TEM QUE DESAPARECER

IF VERDADE
SUB NUM1 ; ESTA LINHA TEM QUE FICAR

STORE RESULT
STOP

SECTION DATA
NUM1: SPACE
RESULT: SPACE
CONSTANTE: CONST VALOR_CONST